### PR TITLE
Reverse the order of the output by default (newest at top) 

### PR DESCRIPTION
**Pull request by jtsternberg**
Change the default log order to put newest entries at top. Filter the default order, and allow overriding with an "order" query var.

### CODE REVIEW

**Comment by norcross** [comment]
I had it backwards because depending on how big the log file is, it can truncate the last one on the file. did you test for that?

**Comment by jtsternberg** [comment]
I'm not sure I super understand what you mean, BUT, the log file I was testing with was definitely truncated, as it was way too big to be showing the whole thing.

**Comment by norcross** [comment]
I'll try to find some of the examples I had

**Comment by jtsternberg** [comment]
K, let me know and I can test.

**Pull request closed without merging**
